global:
  image: "hashicorp/consul:1.13.1"
  peering:
    enabled: true
connectInject:
  enabled: true
dns:
  enabled: true
  enableRedirection: true
server:
  exposeService:
    enabled: true
controller:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1

